sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install codecov.io coveralls

script:
  - yarn run test
  - yarn run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

env:
  global:
    - CI: true
